# Default Value: -1

seed = 520

[author]
name = "Pengpeng Wu"
email = "peg2_wu@163.com"

[data]
save_dir = "../data/mnist"

[model]
mlp_hidden = [784, 256, 10]

[train]
lr = 0.001
train_batch_size = 512
valid_batch_size = 1024
epochs = 100
is_peft_model = true

# 打印日志
print_logs_global_steps = 10

# 保存训练状态
save_state_global_steps = 100
save_state_dir = "../checkpoints"

# 断点续传
resume_dir = -1
# resume_dir = "../checkpoints/global_step_400"

# valid
valid_strategy = "epoch"
valid_steps = 1

# tensorboard
tb_log_dir = "../tensorboard"
tb_record_global_steps = -1    # Default: tb_record_global_steps == print_logs_global_steps
